### ISSUE TITLE
Admin UI for group creation and editing

### ISSUE THREAD

**Issue by bion** [distributeaid/shipment-tracker#10]
Background: the legacy react front-end (see background in #5) has a form for creating groups, but the shape of the data is different from what is needed for this project. I suggest taking a look at that code and seeing if it's worth migrating it over or writing this feature from scratch.

Done when: admins can create and edit groups using the UI

**Comment by romanpohorecki-zz** [comment]
Here's a wireframe draft for users and groups. The assumption here is that users have group labels, and this approach could probably work for shipments or offers.  
https://www.figma.com/proto/hyFkOYybFqxJ3WkwSmkFWf/DA-Toolbox-Visual-Design?node-id=514%3A8058&viewport=994%2C605%2C0.3741587996482849&scaling=min-zoom

Note: there are a lot of features drawn here that are beyond V1 and they're intended for future proofing.

**Comment by deammer** [comment]
Creating groups will be possible after #65 is merged. Editing groups requires #67 to be merged first.

**Comment by deammer** [comment]
Reopening because we still need to add group creation to the UI
