### ISSUE TITLE
As a Group Leader, I can only see a subset of all shipments

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#130]
Group leaders should only see shipments with a status that's one of `ANNOUNCED`, `OPEN`, or `STAGING`.

### Notes

- admins should remain unaffected
- this depends on the work in #129

**Comment by coderbyheart** [comment]
Is this a frontend task, or should this be handled in the backend?

**Comment by deammer** [comment]
This is a frontend task because I don't think it's a security issue if someone manages to bypass our API and list all the shipments.
