### ISSUE TITLE
As a Group Leader, I can only create offers for an OPEN shipment

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#131]
Group leaders should only be able to create offers for a shipment in the `OPEN` status. This restriction should be enforced on the backend and frontend.

For example: if a shipment has the `DRAFT` status, a group captain should _not_ be allowed to create offers for that shipment.

**Comment by coderbyheart** [comment]
This limitation was already present in the backend, however #215 adds an additional test for this behavior.

**Comment by deammer** [comment]
Markus wrapped this up.
