### ISSUE TITLE
Shipment update and show API

### ISSUE THREAD

**Issue by bion** [distributeaid/shipment-tracker#20]
Background: see `Shipment` type in proposed [GraphQL schema here](https://www.notion.so/distributeaid/Technical-requirements-c2fd190e0a8d4f708119c6944fa654dd#ee90467d687d4d158a5a97d131c7a862).

Done when graphql API supports listing all shipments and querying for a single shipment by ID.

Depends on #19

**Comment by andyjac** [comment]
__NOTE:__ Querying all shipments was added in #43 since it was useful while testing shipment creation. The work in this ticket will include adding API support for updating shipments and querying a single shipment by ID instead.
