### ISSUE TITLE
Make sure sending groups cannot see each other's offers

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#244]
For example, sending group A should not be able to see Sending group B's offers.

**Comment by coderbyheart** [comment]
This test ensures that other users can't see the offers for a group's shipments:

https://github.com/distributeaid/shipment-tracker/blob/b2e49dd71fcb8d177c4520363f85aaa27cde4b23/src/tests/offers_api.test.ts#L408-L416

**Comment by deammer** [comment]
Confirmed in the UI 👍
