### ISSUE TITLE
convert clever-cloud infrastructure to code, using the Clever Cloud CLI

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/shipment-tracker#343]
Right now the configuration is only maintained via the Clever Cloud UI

**Comment by juliandm** [comment]
Is this intended to be handled via a bash script? 
There is no terraform provider for clever cloud as of now

**Comment by coderbyheart** [comment]
I'd solve it using GitHub actions which is a fancy bash script, yes.

**Comment by coderbyheart** [comment]
I started looking into this, but discovered that the Clever Cloud CLI does not actually allow you to manage an application from scratch. The CLI allows (like the web application) to interact with a running instance, but is has no features that would for example allow to create a new instance from scratch based on the existing application configuration.
