### ISSUE TITLE
The system doesn't pick up on the isAdmin flag

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#389]
I've registered on https://shipment-tracker-saga.distributeaid.dev and set the `isAdmin` flag to `true`. However, the system doesn't seem to pick up on that flag and prevents me from running admin operations.

For example, I've tried to create a DA Hub with my admin account (id: 3) but I receive the error below:

<img width="1029" alt="Screen Shot 2021-10-11 at 7 46 25 PM" src="https://user-images.githubusercontent.com/3411183/136882597-8175bf5d-43e2-4118-960b-de0731792273.png">

**Comment by coderbyheart** [comment]
Did you log out and in again after setting the flag?

**Comment by deammer** [comment]
@coderbyheart yes, and once again after clearing my cookies and local storage.

**Comment by coderbyheart** [comment]
Yes, confirmed.

**Comment by coderbyheart** [comment]
I think the issue is somewhere with the Apollo configuration, it seems the authentication mechanic does not pick up the flag.
