### ISSUE TITLE
Handle expired cookie in the frontend

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/shipment-tracker#462]
Once the cookie expires there is nothing to do instead of logging in again.

- [x] detect if auth cookie times out without user activity
- [x] force logout and show login screen with a message that informs the user about the automated logout

**Comment by shavidze** [comment]
Could you advise anything? I would like to implement this fix

**Comment by shavidze** [comment]
When I'm trying to run frontend locally, getting this error 
![image](https://user-images.githubusercontent.com/23502763/143012834-6cf06ba2-0152-4dee-9e62-93b9afaa166d.png)

And I'm not seeing that **api-types** in types as well

![image](https://user-images.githubusercontent.com/23502763/143013057-6ddd981e-8f5f-4a77-a2d3-f8b7412a4845.png)

**Comment by coderbyheart** [comment]
Hei @shavidze,

thanks for looking into this.

It seems you did not follow our [README](https://github.com/distributeaid/shipment-tracker/blob/saga/README.md#dev-setup)  on how to get the project up and running.

**Comment by coderbyheart** [comment]
The frontend also has a dedicated [README](https://github.com/distributeaid/shipment-tracker/tree/saga/frontend#development-setup).

**Comment by shavidze** [comment]
I read the frontend README but still the same error. Could you tell me from the image it seemed there is no  **api-types** ts there? why?

**Comment by coderbyheart** [comment]
Which setup type are you using?

**Comment by deammer** [comment]
The `api-types.ts` file is autogenerated by the `graphql-codegen` command. Maybe it didn't work on your machine for some reason?

If you're in the root of the repo, run:
```shell
yarn build
```

And please let us know if you encounter any errors. Looking at your screenshot, it looks like you're trying to run the project locally on Windows, is that right?

**Comment by shavidze** [comment]
hmm yep, you're right. Thanks.
Can I take this issue?

**Comment by shavidze** [comment]
P.S There are no validation error messages on registration form, don't you think to use react-hook-form or formik for validations.
User does not see if he/she is going to login or register , Loader would be a good fit for it

**Comment by coderbyheart** [comment]
> hmm yep, you're right. Thanks. Can I take this issue?

Yes, sure.

**Comment by coderbyheart** [comment]
> P.S There are no validation error messages on registration form, don't you think to use react-hook-form or formik for validations. User does not see if he/she is going to login or register , Loader would be a good fit for it

Not sure what you mean, and out of scope of this issue. Kindly open a [new discussion](https://github.com/distributeaid/shipment-tracker/discussions) .
