### ISSUE TITLE
Unable to create new shipments because of missing ShipmentPricingInput

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#468]
1. Navigate to `/shipments/new`
2. Attempt to create a new shipment
3. See error message:
```
null value in column "pricing" violates not-null constraint
```

<img width="735" alt="Screen Shot 2021-11-26 at 10 35 10 AM" src="https://user-images.githubusercontent.com/3411183/143620188-7b5e3fdb-7886-41ec-85ee-4a30e34685bd.png">

## Solution

- [ ] make the `pricing` input [optional](https://github.com/distributeaid/shipment-tracker/issues/468#issuecomment-984416688).

**Comment by coderbyheart** [comment]
The pricing is required as per the GraphQL schema: https://github.com/distributeaid/shipment-tracker/blob/a99ec457902a36910da0fc7c951e2a2f39ee41e4/schema.graphql#L70

I don't have the domain knowledge to understand what it's used for and if it should be that way or not.

**Comment by coderbyheart** [comment]
It seems to describe the pricing for a full and a half palette:
https://github.com/distributeaid/shipment-tracker/blob/a99ec457902a36910da0fc7c951e2a2f39ee41e4/schema.graphql#L174-L189

We need someone to clarify the meaning of this.

Example from the tests:

https://github.com/distributeaid/shipment-tracker/blob/saga/src/tests/shipments_api.test.ts#L237-L248

**Comment by coderbyheart** [comment]
From the [specs](https://www.notion.so/Technical-requirements-c2fd190e0a8d4f708119c6944fa654dd?d=9ae7a9939ea94430a0fbfe4699974383#9df8b2d5d71d49dcbe439cd4a1144e39):

Q: Why is this requirement listed under the sending hub  requirement? Are prices different based on sending hub? I.e. is the per-pallet rate not the same for everyone in a given shipment? If not, can it be for the first version of this or would that be too minimal to be of use?

A: This spec is here as the Logistics Coordinator can decide the per-pallet price. Prices per pallet depends on the shipment, but not the hub. If we decide to do a shipment to Calais, the per-pallet rate will be the same, irrespective of where the hub is. If we were to do a shipment to Greece, the per-pallet price would be different. The price will change over time for the same route, if there are market shocks (for example, Brexit) and our price model will have to account for this. Not really v1 as we still only have one route (UK to Calais)

Q: Do we need to provide two price specifications, one per pallet and one per half-pallet?

A: Yes, separate specifications please, set at Shipment creation. We don't know how pricing will look in future, can't guarantee a half pallet will just be half the price of a full pallet.

**Comment by coderbyheart** [comment]
This was added in #107, however one key detail from the specs was missed:

> v1 **Optionally** specify prices for the shipping on the route for visibility to sending groups. (In money per pallet or money per half pallet.)

The pallet price configuration should be made optional.

**Comment by coderbyheart** [comment]
> The pricing is required as per the GraphQL schema:
> 
> https://github.com/distributeaid/shipment-tracker/blob/a99ec457902a36910da0fc7c951e2a2f39ee41e4/schema.graphql#L70
> 
> I don't have the domain knowledge to understand what it's used for and if it should be that way or not.

To clarify, it is **NOT** required as per the schema.

**Comment by coderbyheart** [comment]
There were some leftovers in the database migration file that caused this error. 

Remember that you have to reset your local database to see the changes:

```
npx sequelize-cli db:drop
npx sequelize-cli db:create
npx sequelize-cli db:migrate
```

After that, your DB will be blank.

I've done this for the preview system as well.
