### ISSUE TITLE
Setup a React front-end

### ISSUE THREAD

**Issue by bion** [distributeaid/shipment-tracker#5]
Done when react is set up with:

* development server with automatic code reloading
* typescript
* apollo-client connecting to the server's graphql endpoint

DA already has a react project that uses typescript and apollo-client [here](https://github.com/distributeaid/toolbox/tree/saga/react_ui). It's also set up with auth0, tailwindcss, and a basic layout. The best way to approach this task is probably to migrate that code over to this project.

**Comment by deammer** [comment]
👋  snagging this task
