### ISSUE TITLE
Add end-to-end tests on the frontend

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#83]
We were chatting about https://cypress.io or https://playwright.dev

**Comment by deammer** [comment]
Let's wait until v1 ships so that the UI is less likely to change in a major way.

**Comment by coderbyheart** [comment]
However this could help with updating dependencies, this would add a sanity check to verify that basic features which will be there anyway (like login and logout), are still working.

**Comment by coderbyheart** [comment]
Implemented in #228
