### ISSUE TITLE
Group mutate API

### ISSUE THREAD

**Issue by bion** [distributeaid/shipment-tracker#9]
Background: see `Group` type in proposed [GraphQL schema here](https://www.notion.so/distributeaid/Technical-requirements-c2fd190e0a8d4f708119c6944fa654dd#ee90467d687d4d158a5a97d131c7a862).

Done when graphql API supports creating and updating groups

**Comment by Sgtpluck** [comment]
@bion it's unclear from the notation -- is Location and ContactInfo also objects in the database or JSON? I'm assuming they are their own tables, which means they have to be created before Group can be modified, yes?

**Comment by bion** [comment]
@Sgtpluck seems like it could be implemented either way. An additional table seems like a reasonable approach. I'd be fine with either so long as the implementation supports the GraphQL-defined schema.

**Comment by bion** [comment]
@Sgtpluck thinking about it a little more I wonder if storing those in JSON columns wouldn't be the easiest. I can't think of a strong reason to prefer a normalized DB schema.

**Comment by deammer** [comment]
@Sgtpluck I just merged #44 where I added the `groupType` field to the `Group` model, so I recommend pulling the latest code when you work on this.

**Comment by Sgtpluck** [comment]
closed with #51
