### ISSUE TITLE
The client-side cache doesn't refresh when creating entities

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#95]
In #94, we discovered that when a new shipment is created, the list of shipments is not refreshed. We need to figure out how to fix it and document the best practices!

### Repro steps

1. View the list of shipments
2. Create a new shipment
3. Go back to the list of shipments

**Expected result:** the new shipment is displayed in the list

**Actual result:** the new shipment is absent from the list

**Comment by coderbyheart** [comment]
Apollo has a strong focus on client side caching and offline support, this typically happens because the internal cache is not updated after the mutation.
This is mentioned here: https://www.apollographql.com/docs/react/data/mutations/#making-all-other-cache-updates
